export const products = [
    {
        id: 1,
        name: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        price: 109.95,
        description: "Tu mochila perfecta para el día a día y los paseos por el bosque. Guarde su computadora portátil (hasta 15 pulgadas) en la funda acolchada, su diario",
        category: "hombre",
        stock:10,
        img: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"
    },
    {
        id: 2,
        name: "Mens Casual Premium Slim Fit T-Shirts ",
        price: 22.3,
        description: "Estilo ajustado, manga larga raglán en contraste, tapeta henley de tres botones, peso ligero y tela suave para un uso cómodo y transpirable. Y camisas con costuras sólidas con cuello redondo hechas para mayor durabilidad y un gran calce para la ropa de moda casual y los fanáticos del béisbol acérrimos. El escote redondo estilo henley incluye una tapeta de tres botones.",
        category: "hombre",
        stock:10,
        img: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    },
    {
        id: 3,
        name: "Mens Cotton Jacket",
        price: 55.99,
        description: "Grandes chaquetas de abrigo para primavera/otoño/invierno, adecuadas para muchas ocasiones, como trabajo, senderismo, camping, montaña/escalada, ciclismo, viajes u otras actividades al aire libre. Buena opción de regalo para usted o su familiar. Un cálido amor al padre, esposo o hijo en este día de acción de gracias o Navidad.",
        category: "hombre",
        stock:10,
        img: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    },
    {
        id: 4,
        name: "Mens Casual Slim Fit",
        price: 15.99,
        description: "El color podría ser ligeramente diferente en la pantalla y en la práctica. / Tenga en cuenta que las construcciones corporales varían según la persona, por lo tanto, la información detallada sobre el tamaño debe revisarse a continuación en la descripción del producto.",
        category: "hombre",
        stock:10,
        img: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    },
    {
        id: 5,
        name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
        price: 695,
        description: "De nuestra colección Legends, el Naga se inspiró en el mítico dragón de agua que protege la perla del océano. Úselo mirando hacia adentro para recibir amor y abundancia, o hacia afuera para protección.",
        category: "accesorio",
        stock:10,
        img: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        id: 6,
        name: "Solid Gold Petite Micropave ",
        price: 168,
        description: "Satisfacción garantizada. Devuelva o cambie cualquier pedido dentro de los 30 días. Diseñado y vendido por Hafeez Center en los Estados Unidos. Satisfacción garantizada. Devuelva o cambie cualquier pedido dentro de los 30 días.",
        category: "accesorio",
        stock:10,
        img: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        id: 7,
        name: "White Gold Plated Princess",
        price: 9.99,
        description: "Anillo de promesa de diamante solitario de compromiso de boda creado clásico para ella. Regalos para consentir más a tu amor por Compromiso, Boda, Aniversario, San Valentín...",
        category: "accesorio",
        stock:10,
        img: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        id: 8,
        name: "Pierced Owl Rose Gold Plated Stainless Steel Double",
        price: 10.99,
        description: "Pendientes tipo túnel con doble acampanado chapados en oro rosa. Hecho de acero inoxidable 316L",
        category: "accesorio",
        stock:10,
        img: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        id:9,
        name: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
        price: 64,
        description: "Zapatillas deportivas arriba alta de hombres con estampado de grafiti",
        category: "zapatilla",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2020/10/21/1603251473a29b3b6157e3785765b221c41cf3dcf4_thumbnail_900x.webp",
    },
    {
        id: 10,
        name: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb / s",
        price: 109,
        description: "Hombres Zapatillas de skate con estampado de letra con cordón delantero",
        category: "zapatilla",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/08/04/1628075355dc6fc8f768786ded6b587e9749bf5500_thumbnail_900x.webp",
    },
    {
        id: 11,
        name: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
        price: 109,
        description: "Hombres Zapatillas deportivas chunky con estampado de letra arriba alta",
        category: "zapatilla",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/09/07/163098573239bf8773cacd55afab9975535704752a_thumbnail_900x.webp",
    },
    {
        id: 12,
        name: "Zapatilla planta baja",
        price: 114,
        description: "Espadrillas ribete crudo",
        category: "zapatilla",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/09/11/1631293517b9edbeca179f1d63fc711a747e0a96ba_thumbnail_900x.webp",
    },
    {
        id: 13,
        name: "Acer SB220Q bi 21.5 inches Full HD(1920 x 1080) IPS Ultra - Thin",
        price: 599,
        description: "Botas de combate con cordón delantero minimalista",
        category: "zapatilla",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2020/09/24/1600936473b819a992689b59fd85b164ea9a4363eb_thumbnail_900x.webp",
    },
    {
        id: 14,
        name: "Samsung 49 - Inch CHG90 144Hz Curved Gaming Monitor(LC49HG90DMNXZA) Super Ultrawide Screen QLED ",
        price: 999.99,
        description: "Zapatillas de skate de dos tonos con cordón con diseño de lona",
        category: "zapatilla",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/08/19/1629356557ebffc35f010af9089d0f62ff77f77042_thumbnail_900x.webp",
    },
    {
        id: 15,
        name: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
        price: 56.99,
        description: "Nota: Las chaquetas son de tamaño estándar de EE. UU., elija el tamaño que usa habitualmente. Material: 100 % poliéster; Forro desmontable: forro polar cálido. Forro funcional desmontable: respetuoso con la piel, ligero y cálido. Chaqueta con forro de cuello alto, te mantiene caliente en climas fríos. Bolsillos con cremallera: 2 bolsillos con cremallera para las manos, 2 bolsillos con cremallera en el pecho (suficientes para guardar tarjetas o llaves). ) y 1 bolsillo oculto en el interior. Los bolsillos para las manos con cremallera y el bolsillo oculto mantienen sus cosas seguras. Diseño humanizado: capucha ajustable y desmontable y puño ajustable para evitar el viento y el agua, para un ajuste cómodo. El diseño desmontable 3 en 1 brinda más comodidad, puede separar el abrigo y el interior según sea necesario, o usarlos juntos. Es adecuado para diferentes estaciones y lo ayuda a adaptarse a diferentes climas.",
        category: "mujer",
        stock:10,
        img: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    },
    {
        id: 16,
        name: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        price: 29.95,
        description: "100 % POLIURETANO (exterior) 100 % POLIÉSTER (forro) 75 % POLIÉSTER 25 % ALGODÓN (JERSEY), Material de piel sintética para estilo y comodidad / 2 bolsillos en la parte delantera, 2 - For - One Chaqueta de piel sintética estilo denim con capucha, Detalle de botones en cintura / Detalle de costuras en los costados, LAVAR A MANO SOLAMENTE / NO USAR LEJÍA / SECAR AL LÍNEA / NO PLANCHAR",
        category: "mujer",
        stock:10,
        img: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    },
    {
        id: 17,
        name: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        price: 39.99,
        description: "Ligero perfecto para viajes o ropa informal -- - Manga larga con capucha, diseño de cintura con cordón ajustable. Chubasquero con cierre frontal de botón y cremallera, totalmente forrado a rayas y El impermeable tiene 2 bolsillos laterales son de buen tamaño para guardar todo tipo de cosas, cubre las caderas, y la capucha es generosa pero no exagera. La capucha forrada de algodón con cordones ajustables le da un estilo real.",
        category: "mujer",
        stock:10,
        img: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    },
    {
        id: 18,
        name: "MBJ Women's Solid Short Sleeve Boat Neck V ",
        price: 9.85,
        description: "95 % RAYÓN, 5 % SPANDEX, Fabricado en EE. UU. o importado, No usar lejía, Tejido liviano con gran elasticidad para mayor comodidad, Acanalado en mangas y escote / Doble costura en el dobladillo inferior",
        category: "mujer",
        stock:10,
        img: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    },
    {
        id: 19,
        name: "Opna Women's Short Sleeve Moisture",
        price: 7.95,
        description: "100 % poliéster, lavar a máquina, 100 % interlock de poliéster catiónico, lavar a máquina y preencogido para un gran ajuste, ligero, espacioso y muy transpirable con tela que absorbe la humedad que ayuda a mantener la humedad alejada, tela suave y ligera con cuello en V cómodo y un ajuste más delgado, ofrece una silueta elegante y más femenina y mayor comodidad",
        category: "mujer",
        stock:10,
        img: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    },
    {
        id: 20,
        name: "DANVOUY Womens T Shirt Casual Cotton Short",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "mujer",
        stock:10,
        img: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    },
    {
        id: 21,
        name: "POLO VERANO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.1098819889.5785/ssrco,classic_tee,two_models,5e504c:7bf03840f4,front,square_three_quarter,1000x1000.jpg",
    },
    {
        id: 22,
        name: "SIN INTERNET DINO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.1010277927.8243/ssrco,classic_tee,flatlay,5e504c:7bf03840f4,front,wide_portrait,750x1000.jpg",
    },
    {
        id: 23,
        name: "CAMISAS CON TIRANTES CONDOR",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.95608680.6104/ra,tank,x1850,101010:01c5ca27c6,front-c,95,35,1000,1000-bg,f8f8f8.jpg",
    },
    {
        id: 24,
        name: "CAMISA CON AVE",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.211864532.5673/ra,tank,x1850,fafafa:ca443f4786,front-c,95,35,1000,1000-bg,f8f8f8.u1.jpg",
    },
    {
        id: 25,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.215047620.4430/ssrco,slim_fit_t_shirt,flatlay,e0e1dd:064437a66d,front,wide_portrait,750x1000-bg,f8f8f8.u1.jpg",
    },
    {
        id: 26,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.552985259.4898/pencil_skirt,x1000,front-c,378,0,871,871-bg,f8f8f8.jpg",
    },
    {
        id: 27,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.499289230.5470/aldr,x1700,front-c,60,103,1000,1000-bg,f8f8f8.u4.jpg",
    },
    {
        id: 28,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "verano",
        stock:10,
        img: "https://ih1.redbubble.net/image.709070293.6954/leggings,m,x900,back-pad,750x1000,f8f8f8.u4.jpg",
    },
    {
        id: 29,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "invierno",
        stock:10,
        img: "https://ih1.redbubble.net/image.215047620.4430/ssrco,mhoodiez,mens,oatmeal_heather,front,square_three_quarter,1000x1000-bg,f8f8f8.u1.jpg",
    },
    {
        id: 30,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "invierno",
        stock:10,
        img: "https://ih1.redbubble.net/image.231419152.7419/ssrco,lightweight_hoodie,womens,101010:01c5ca27c6,front,square_three_quarter,x1000-bg,f8f8f8.1u2.jpg",
    },
    {
        id: 31,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "invierno",
        stock:10,
        img: "https://ih1.redbubble.net/image.1099445633.6122/ssrco,mhoodie,mens,fafafa:ca443f4786,front,square_three_quarter,x1000-bg,f8f8f8.1.jpg",
    },
    {
        id: 32,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "invierno",
        stock:10,
        img: "https://ih1.redbubble.net/image.250675597.9621/ssrco,mhoodie,womens,fafafa:ca443f4786,front,square_three_quarter,x1000-bg,f8f8f8.1u2.jpg",
    },
    {
        id: 33,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "otoño",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/09/16/16317691860a839b22ea6fb5931f759b28a1822422.webp",
    },
    {
        id: 34,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "otoño",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/07/31/1627722743b2a60ff78fc0285da1fa35f6c3ee7b00.webp",
    },
    {
        id: 35,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "otoño",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/10/07/1633538757e9f7e0964a0bbffb07c27b242387f14c.webp",
    },
    {
        id: 36,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "otoño",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/12/22/16401397012961af8d7f1e3bb38a76288f70eff78f_thumbnail_900x.webp",
    },
    {
        id: 37,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "primavera",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/10/13/16341182256d82523bac853d92afed29f466fd0f41_thumbnail_900x.webp",
    },
    {
        id: 38,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "primavera",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/09/27/1632714088aab2b9cf74625b52b2d910d66aa8fc76_thumbnail_900x.webp",
    },
    {
        id: 39,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "primavera",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/11/27/1637998693e7707756efc793eecaca50d9db8fc0ce_thumbnail_900x.webp",
    },
    {
        id: 40,
        name: "GATO ,RASGANDO",
        price: 12.99,
        description: "95 % Algodón, 5 % Spandex, Características: Informal, Manga corta, Estampado de letras, Cuello en V, Camisetas de moda, La tela es suave y tiene algo de elasticidad., Ocasión: Informal / Oficina / Playa / Escuela / Hogar / Calle. Temporada : Otoño invierno Primavera Verano.",
        category: "primavera",
        stock:10,
        img: "https://img.ltwebstatic.com/images3_pi/2021/12/23/1640236114b00f2eaee795e72727137a6a809d7f77_thumbnail_900x.webp",
    },

];

export const traerProductos = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(products);
    }, 2000);
});
